key: ENC[AES256_GCM,data:VyA1AKAi1ObuBHVAvqxe4wAu9geJc7yLDbb3u5yEy9ZXUkwjSz1M9bDmI294IowUkj8dqJiT8YdKhvwLt90YfAeuH8bryqR3oAus,iv:p+5kiW3JXpm728/4hzRFUYJ10MNispYM1w70Z43e3n8=,tag:MsI/BCQgtutAqhj6A5Z7Pw==,type:str]
sops:
    age:
        - recipient: age1yubikey1qvz5vfsh7xv4wvt7c8jxjzh9vgqpnvvnyc5pdxtyq22uacyyjuepxl5v39h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFk0cG5vZyBBM2VUVTBU
            cUU5R2FQT3pMZTYrc1NYUWdyYVFja3IrdnBKdHdGSlBhQUlnYQpwVDB1TTYwQ005
            OFpmM1Q3M2gwMlZPRGxodUVEZmY5ODEwNGtURFF4MzVNCi0tLSBTSmV5MFdhbWdV
            WS9iejJlOHQyUjZNaVNoc3NyQUtKaWNpUlM4Q1ZCL1Q0CpHTc2JIi8s5lBLDSsLr
            PhQ3WaAaJRaYHxAG5znvL1yQpELvjtG5jGQtJvxdmn2TPQkqPW5DxsLj0rVA6c5g
            Az8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2nwpd9tj446fluvv3pgexq8vq669aq0c8tt6d09z0hhzgkmrh7dszy0hs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFZnTHNPUSBBdFE2U29W
            cmsvVXdCU3F5dU9qK1FvNTBlL1RrQllBczZ2ZW9iRXZscitjYQo4cTBaVHhVWFZ3
            MURyUHJ1UW5LWDY1ZnkvTnpaZUNCaGFmNzYzbHVKc1JVCi0tLSBkMVE5cUZXZlZo
            TjNWV2dselBNa3BHaytiK3FQN1VBai9HaXZqaTR1Tm9zChQqTbs5oTPruJM1XEfn
            yGQvBni7SPfQddqEXjcx9YnKtL+8jjh8W8M+jT0LWPQqa9u7OWa4Bt9lfJ/pdlb3
            FGU=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15p8k9vll4k7uqgmqydcn5n09dzc4dlw4nq6zwlnunnurpxg8wqlsyu9mlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SnFzVVU4Qmk0OW5ZamZv
            OFkwNUVWR1ZpRTQxaW4wdW1lbEl6UldXb2hRClNYbGpvY1k2bk5LbFduOW9RMFdU
            TS9BTU5RUTlpb3Q4NWx5WFZhNVdPZ3MKLS0tIE5nUWx1YzFhVDFJZDViUmE5MWNB
            aEp2ZXY3dkxXc3ljM04wWWZUZnFwNlUKVNfYdt9vtcIPr4eFDJJTZcfHgQ5IR0OR
            gQRaXmidRGsTGcdSrx4QdHosY9gm80XL9eGpWYpTD3LLDhKTWgOCiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e4scgj83r7yddwk96sm8ghdes309e7lze2rq73ufmngkhpaa74vsqndxsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0R1BYRit5dUhndFdJcWdt
            Y2dzVytmMzVQSHp6YjB0V1FYZW40QlFLSVM4CmpqajZjYVA5bDgrR3ZEdWFCbUJk
            NEZhUmRJcG0veVZuRmhBNzY1eEdjMG8KLS0tIGo2dURtdG5YVEFtUVQ5Si9iaDBP
            djdmQUVjcERzUUtrU2FpVG1pS04xR2MKXvVO2cLdnw1y2BLf/yJBqP8GXor4nwfV
            1spnMMioKyRkGpXV7c1apEO3qlRf92wE3yGdNHD3BbEnRV9H110U3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T09:50:32Z"
    mac: ENC[AES256_GCM,data:Qf2j+S1wtePgcJQf2OR3XPHjxp0/GyKykrPN7wHGpd8Ho7gQztHPjykKVLIcIzoao7Ex5MsAR4QeaKcdFzA9Vkw8KDeTLDUjI2IMDqN7EA847MTTXPd+lf5h9VxODwo2SOOlSiHC9xJOvBKV9Rl40GKYsCF6QHkQNMKCWP0Fk7c=,iv:3dSS7zE2M/sMSfoTSOFWhAYsD0PJvOufFNVnOyeb2W0=,tag:KNP01o2sNyq/43G3cWFH4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
