key: ENC[AES256_GCM,data:VyA1AKAi1ObuBHVAvqxe4wAu9geJc7yLDbb3u5yEy9ZXUkwjSz1M9bDmI294IowUkj8dqJiT8YdKhvwLt90YfAeuH8bryqR3oAus,iv:p+5kiW3JXpm728/4hzRFUYJ10MNispYM1w70Z43e3n8=,tag:MsI/BCQgtutAqhj6A5Z7Pw==,type:str]
sops:
    age:
        - recipient: age15p8k9vll4k7uqgmqydcn5n09dzc4dlw4nq6zwlnunnurpxg8wqlsyu9mlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OURaT3dsdk5kNStqWk5r
            dEdCZ2dCMzR3MWtuZTJQQ05qcWp1TVFxQjBnCjNWK2FwbzdkYW5FVW10Wlh2ODJV
            cDVJdit4WS9yT2VmcEZzeDcvckozTFUKLS0tIHArSjJ3WlpvUkQ5RVl5dE5jcDlu
            SlQ3RVYwY0k1WVJqb3ZrNGFnemx2aU0KFLp5jwJBFIKIBYzbymS4s8t3J+m0ZjnE
            eA0uR9U0iredEwDbXkiEuutAyxGmg9UI8Rm3cGupntkzM8xpC2oDkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e4scgj83r7yddwk96sm8ghdes309e7lze2rq73ufmngkhpaa74vsqndxsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cENFcGhsUFVEa3ZSR0lt
            bkpKdkR6d2syNVJtcnYxSUVpckM2RmhHaEJzCi96clk0M0VtcTZ5ZXRPcThBc0dU
            NlhBb0QySXNrV3NBMXkyRXRKSmY5K2sKLS0tIHJXbmVHUHlRbFplakNIbDJZbTNR
            Y1A1L0FZaWlBazdOeVAyejFXT0Mrb0UK8EzVbiTPot0m7/o0BOIq0fv0XndASe9a
            iN13aCbgyIpfiD7YPeZOfsjTkbbbf+XjNPbFXbonwzX71rLmWiPutg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T09:50:32Z"
    mac: ENC[AES256_GCM,data:Qf2j+S1wtePgcJQf2OR3XPHjxp0/GyKykrPN7wHGpd8Ho7gQztHPjykKVLIcIzoao7Ex5MsAR4QeaKcdFzA9Vkw8KDeTLDUjI2IMDqN7EA847MTTXPd+lf5h9VxODwo2SOOlSiHC9xJOvBKV9Rl40GKYsCF6QHkQNMKCWP0Fk7c=,iv:3dSS7zE2M/sMSfoTSOFWhAYsD0PJvOufFNVnOyeb2W0=,tag:KNP01o2sNyq/43G3cWFH4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
