secret: ENC[AES256_GCM,data:767OggBw7EabOYVdfjeQbJKxf+n6LElz+r0F3lr+M2LkJ3FZVaTeglxEoBVEuX2yfAmaiL5TU2X/t7PnImrjXw==,iv:sDwU6wjKNTnOxbuL4sI4EWgqbMZxYBRNBr9nPotDvz4=,tag:Gx6zwUhENUccmea5D9w32w==,type:str]
sops:
    age:
        - recipient: age1yubikey1qvz5vfsh7xv4wvt7c8jxjzh9vgqpnvvnyc5pdxtyq22uacyyjuepxl5v39h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFk0cG5vZyBBNFpVejZN
            M0Nqd0FUamU2ZEs0ZHVsU0VRMmZBZFBYM0pJTWlPYUxiRHpXQwpCamxRd2xZNmRE
            emRjNjhNamFyZC9DRXE3QW5pQVhZUG9lQnYrWk9zaUdZCi0tLSA3dldFb2hNWERU
            S29XK0t5NElaa1F5b3pwbFFaNFVpaktkMlFtY1NabGJNClJq388p9Rfjpr9FtxlI
            qNjXMFH1j7hdwxBoLlnjfGqzLGsRTK6tNoTcBNa+JSqCOIxcQ4BAKUZbSGimRO5h
            vjY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2nwpd9tj446fluvv3pgexq8vq669aq0c8tt6d09z0hhzgkmrh7dszy0hs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFZnTHNPUSBBdkNHeGFZ
            aDNmTktsMHFTYjBNQW9XcHl6QU9FREl0cnFkdlJYSGNiTWlIZQo1UkNqZnBweStj
            ekhlQ3JRalJhR2NXemZ2Z01MSkw0MlNiZlFaMzFoeDFFCi0tLSBiY3AwV2FpS002
            Z3dPUEVVTE44VnVhTThhWldRdk5qalZVZDhEVTZoNFpJCietBrLA+5FaogIuSSDu
            Daa2cVv2IdBCxizpVUyoP30WlFLs8XAjZWYc195LcJQIE46AIEOydf9RlLEhzuQe
            G7U=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15p8k9vll4k7uqgmqydcn5n09dzc4dlw4nq6zwlnunnurpxg8wqlsyu9mlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV0k5d0hwTGxQOFNQTnFT
            ZGJPSWdPU3pkNEUvaXlQVEpldEpZSTB1RTFjClNSZHFDSTRlcGFQMFJTblBKTFA4
            Y3FyV1d3RUF4Vzc5VWxUdno4TjF3MHMKLS0tIEtsVU4vczV6RzFpQitFZ2JucEc4
            OEhiaHhOQ1QwVlRhUjNvWm9qczU0NDAK85WBKdncKBpTQv4UX+djeCro5VCUw2br
            wFHseK5UJBxMHOylEYZ0Kq1jFK3j97jfgqKHL7ntFoepaWaZzjwy7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e4scgj83r7yddwk96sm8ghdes309e7lze2rq73ufmngkhpaa74vsqndxsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNemhaSG5vWjYxSnBCWkhW
            ZnRVbDRnNG9hRGxiQUVoVlBjYWMwaXdvWERNCkVlQ3lKU3cwckNqYlZHRXJ6T1pD
            ZWdTZ3ZWY1RuTGVhcUNDK3JZSFVmRDgKLS0tIElhNWhYSzlSblNoemJXdzdaQlVz
            aGVlSTVuZDdXeVJSMndTbk40TEV4VEEKy0lXUVbCv7CQvaebiQ0jn9ak4cWAuNAS
            in2p7K3d0bam6MosnSqYkqv5TG5EoxpI/NPFDL/RcnSFNp9lq5BSdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rq0nrc44pwvah7ddf42tsgpx7nd9qrl88a5c553yt0vk8g2kqpds5ft5qe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YXZjRkdtcDNleTkvamJU
            S1laYzlSUjRTdGlwOE9XWXUvRE9teHRMMjBzCmxxbFFUSk8vQnpHVWVRK0YwZ1dU
            NDhZMGF2b1o3TzRWVlMvKzJyaUJqVmMKLS0tIDgzT0E0OFQ4TGVKSlNmSWZMTWJH
            cmRpTVVkRXE3NmlYNjUvUHBYb0tCWTAKlYdxv+lxIYNgDmTxJIQZWojSerhBmwLg
            dhZRKCv7GNmNg82+LsGvG+urSLah6KgBgnzESxnMiKF+3aesRLZkQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T13:41:15Z"
    mac: ENC[AES256_GCM,data:0BwlW/vWXps4ms2WV3YpIKKaFkrnQrr3h3tniveC4QzajEGBE2MIcqF2o00NO3PbvY/wk5bsRwr2aHgJjZPgspxzCuLo50zerXhfxTE3/ViMq1Nf2fGdHJ75VfghZfyOtb1T2pxlpkliLHyMBNsnCbHJBPBivn7W4/YBTYl9b9s=,iv:ODiRRkopCSJX219Ukjf5dL4MIcab2dXHSUDamvdimN0=,tag:k0MPIxbglWG46TMNKN0JdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
