secret: ENC[AES256_GCM,data:767OggBw7EabOYVdfjeQbJKxf+n6LElz+r0F3lr+M2LkJ3FZVaTeglxEoBVEuX2yfAmaiL5TU2X/t7PnImrjXw==,iv:sDwU6wjKNTnOxbuL4sI4EWgqbMZxYBRNBr9nPotDvz4=,tag:Gx6zwUhENUccmea5D9w32w==,type:str]
sops:
    age:
        - recipient: age1yubikey1qvz5vfsh7xv4wvt7c8jxjzh9vgqpnvvnyc5pdxtyq22uacyyjuepxl5v39h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFk0cG5vZyBBcjV4bEZZ
            a0NDVzdIdVZadlR5NDJ0clRKZTdTYmd4UkJxb25hd1IvNmJ6UgpUMFZoWjEzR1Vl
            VStpWDc5bGYxVzZBWDZxdmUzNENHRHF0eTVVSGV3T1BFCi0tLSBhKzdUaVYwaCtr
            U0tlRXhNL3lqUGxwZ3psVGhzRTVoRTlaVnNJNGtuekdjCsmbpiMysR1d4EtyOIyf
            00GEPeq65Bk+vdqLHHOXMzvKh3ldEhcdZq0y+h/522BotMj6C4p4N+yV3cpBgy/3
            CEo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2nwpd9tj446fluvv3pgexq8vq669aq0c8tt6d09z0hhzgkmrh7dszy0hs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFZnTHNPUSBBeWhZYm0r
            QU95dTdSQS9NN1diU0hIaWdXK252a1NyNzBXSHVzSll5OTNiVQpGeHF1VU5kNlVa
            aWJmL0dOdTlTTmhTbSszMCs2S1ljM0loODRmd3p1aEpVCi0tLSBZd2hUT0V1eXdn
            QjY4b1o3Rmx0Yms2Zlk0OEVOc3FvUDFHbEp5aXJERXQ0CjzihpT3mZucEViNXh7x
            l/6vzpPckFV7MVCKNM0KNM5FUFS1OWEI0L1ttLXdKoJ+2x2VOABhwnRO3x/QAErv
            cfE=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15p8k9vll4k7uqgmqydcn5n09dzc4dlw4nq6zwlnunnurpxg8wqlsyu9mlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWTE3bFN3YzBtWWQwVDVD
            QjVJOURUZ0lxajM4bFN6aitLTVFoanZNeGhRCkhWelZiT3BsV3RDWnAzZmZRR0t4
            Znc1TXpRbnVvYmp0OEhMQmcwOGZYeUUKLS0tIElBL1RCUXo0M09mbTNLSXBwR0sx
            Zk96a0I4YUp1Y0V5aENDNTVrcjhiSHMKQyCzctbpuk4/1n6cHWdFmpiiwfxfMB9z
            RAev9BTctJYFUO18rkEl3mI3T4Yr80poXuGmeV1Rr1n3HcOTnVAN6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e4scgj83r7yddwk96sm8ghdes309e7lze2rq73ufmngkhpaa74vsqndxsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNXpHYzlZTE9tVmsrTWNi
            M2ZyaDRiQlU4OFAzWFJ6aGhSQis2MmZ4QVFNCmU3eE9EejR3VUFVd3A5ZStYMTda
            YUtLUGFraHVvZ0sxUm90Qkx3UDluUmsKLS0tIDhDZGxSRm9KSEdNWi90SENueTho
            aDQ0RktMdGRtVk90WEZIUGgzVHJaRk0KfCxA9Jgz6856+vUwIg5rVCYLlmFiXFzx
            rQMqjd08DeK0T1TinEPfDk0WQnKVdNPFI/kViG0B+GGP/Z+VgmRI4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T13:41:15Z"
    mac: ENC[AES256_GCM,data:0BwlW/vWXps4ms2WV3YpIKKaFkrnQrr3h3tniveC4QzajEGBE2MIcqF2o00NO3PbvY/wk5bsRwr2aHgJjZPgspxzCuLo50zerXhfxTE3/ViMq1Nf2fGdHJ75VfghZfyOtb1T2pxlpkliLHyMBNsnCbHJBPBivn7W4/YBTYl9b9s=,iv:ODiRRkopCSJX219Ukjf5dL4MIcab2dXHSUDamvdimN0=,tag:k0MPIxbglWG46TMNKN0JdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
