zai: ENC[AES256_GCM,data:bumNRpP7bSzhGGFrmzBFAo+fBLhci80Df+hFj8scs5WAge0WD375z7Vcfzw9XGNHOg==,iv:oFARAu1kxWh0XXTovPtQuq3waVGSHwjso6rMW5PFzq0=,tag:SbdfCvuB0o8GBMbNp0mmlw==,type:str]
minimax: ENC[AES256_GCM,data:Dt2YJNuAw2Co0xCrxItHGzyHTn13h6uTss0cu0c7lL9+8cPd678+t8cg5JI7zod7wSs3ixtlBlhrOfe61bNBQtwafQm8wdFXgIaX49tSE9pGPK3227fXs+zVINV2HYyblsaSWG/cvl+6C4mC+yUoaGb410cnwj8k5847u6o=,iv:XoTjVOtE4CJW3JlLvpWlymxJ5RZ9jofaS18Q0mUp0PY=,tag:WCv+KqvHOMv06VmwtzSxOQ==,type:str]
sops:
    age:
        - recipient: age15p8k9vll4k7uqgmqydcn5n09dzc4dlw4nq6zwlnunnurpxg8wqlsyu9mlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a0JQNmxZWS93aUpsczlW
            czYyZ2Frcnh0MWhOZVdsa25xNHp5Y0VYZkJVClJKbFNKUE5sYzNMU0FwNVE3Y2Z2
            U0RBU3ZUNmpIejJ4eDVVZFZLUEpJdkUKLS0tIENkYXhhWWJpMlczeWNOd2xTd1R1
            Z2JHbFpSaXN4Tk52TnZ0VS9qUml3QzAKifQhQMYKEeG39Y4PJek459JUUjdVoLa1
            ak+0GL2577Aol4OvbN1NYT2ZGR43if3FBPGhsmMJ4tZzdhRQzCRSxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T20:45:36Z"
    mac: ENC[AES256_GCM,data:8rB5euPGVu29ikgtYI7sCuRZbPMR3kPcLMZsp6B0MoDs+ZeBEaaRvKQxPzrCFd5ND1fqq9/mxRzXu7voM2elA3yXOF3MZekvVWlPHfMh9dGPeT3y1VHhi33q5gYrFuwqFagsui+Ff8tch6yWP4SLQh3B6mlYfZB7vYWlZ2In3E4=,iv:EoCmPM8b9y3wC04NOP5i6bfWspagbhvevmO930FZ7s0=,tag:89QoSKdhQt55SnFn11+N5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
