{ ... }:
{
  imports = [
    ../defs/agents/code-monkey.nix
    ../defs/agents/the-architect.nix
    ../defs/agents/10xBEAST.nix
    ../defs/agents/bottleneck.nix
    ../defs/agents/chaos-demon.nix
    ../defs/agents/code-red.nix
    ../defs/agents/scribe.nix
    ../defs/agents/explore.nix
    ../defs/agents/scout.nix
    ../defs/skills/nix-agents
    ../defs/skills/system-context
    ../defs/skills/1password
    ../defs/skills/granola
    ../defs/skills/grafana
    ../defs/skills/hubble-mcp
    ../defs/skills/linear
    ../defs/skills/lunar-skills
    ../defs/skills/slack
    ../defs/skills/sourcegraph
    ../defs/skills/swe-pruner
    ../defs/skills/work-mcp
    ../defs/skills/home-mcp
    ../defs/skills/xcode
    ../defs/skills/secrets-management.nix
    ../defs/skills/session-heuristics
    ../defs/skills/skill-creator
    ../defs/skills/add-module
    ../defs/skills/parallel-reviews
    ../defs/skills/grill-me
    ../defs/skills/grill-with-docs
    ../defs/skills/grilling
    ../defs/skills/domain-modeling
    ../defs/skills/homelab
    ../defs/skills/last30days
    ../defs/skills/land
    ../defs/skills/mmx-cli
    ../defs/skills/fli
    ../defs/skills/activities-search
    ../defs/skills/agent-browser
    ../defs/skills/google-flights
    ../defs/skills/google-hotels
    ../defs/skills/hotel-search
    ../defs/skills/travel-search
    ../defs/skills/lavish
    ../defs/skills/what-if
    ../defs/skills/plan-x
    ../defs/skills/writing-great-skills
    ../defs/skills/yeet
    ../defs/mcps/1password.nix
    ../defs/mcps/lunar-skills.nix
    ../defs/mcps/granola.nix
    ../defs/mcps/grafana.nix
    ../defs/mcps/linear.nix
    ../defs/mcps/sourcegraph.nix
    ../defs/mcps/swe-pruner.nix
    ../defs/mcps/xcode.nix
    # NOTE: session-write hooks require pkgs and must be wired in flake.nix:
    #   modules = defaultModules ++ [ (import ./defs/hooks/session-write.nix { inherit pkgs; }) ];
  ];
}
